### ISSUE TITLE
Pain Management Summary not working in IE 10 or IE 11.

### ISSUE THREAD

**Issue by senorpatricio** [AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY#17]
In development and in a production environment I am not able to get this working. It's almost like the app is not seen at all when I navigate from the smart app launcher. I have included a polyfill to account for the newer methods being used (map, Object.assign, etc) but it does not seem to affect the behavior of the app. 

Have you had to do anything to make it work with IE10-11?

**Comment by cmoesel** [comment]
Hi @senorpatricio -- we did not target IE 10 or IE 11 during Pain Management Summary development.  It currently works on Microsoft Edge, Google Chrome, Mozilla Firefox, and Mac Safari browsers.  Support for IE 10 would be difficult as [IE 10 reached end of life Jan 12, 2016](https://www.microsoft.com/en-us/microsoft-365/windows/end-of-ie-support).  Support for IE 11 is likely possible, but note that [IE 11 will reach its end of life on November 30](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666).

Based on two commits in a forked version of the Pain Management Summary ([commit 1](https://github.com/uwcirg/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY/commit/9ef1881ee4227cd10aa32fe123096bfdf56e4643), [commit2](https://github.com/uwcirg/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY/commit/21878d6d8ad4a908932cf2bb1691555cb273450a)), it looks like you might be able to achieve IE 11 support by:
* adding `"ie 11"` to the `"browserslist"` entries in `package.json`
* adding `react-app-polyfill` as a dependency
* importing `react-app-polyfill/ie11` and `react-app-polyfill/stable` (potentially instead of `@babel/polyfill`) in `src/index.js`

Please note, however, that I have not tested these changes; I'm only suggesting them based on what I found in commits of a forked project that _does_ appear to target IE 11.

**Comment by senorpatricio** [comment]
Thank you for your response and explanation. I figured it would not be targeted during development as both of those browsers are very old. I have tested what you have suggested from the forked version without any luck. I'll have to go a different route I believe.

Thanks!

**Comment by cmoesel** [comment]
I've just been reminded that we _did_ confirm it working in IE 11 at one point (back in 2018) in order to support the pilot on an Epic system.  Since then, we've upgraded it to support FHIR R4, which required us to "un-eject" react-create-app, upgrade the fhirclient lib (and other libs), and make other changes to the code.  It seems that perhaps in those updates, compatibility with IE 11 was lost.

**Comment by cmoesel** [comment]
Closing. We do not plan to support IE 10 or IE 11.
