### ISSUE TITLE
No medication end dates for r4 Brenda Jackson

### ISSUE THREAD

**Issue by maggiedorr** [AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY#4]
There are no end dates for any of Brenda Jackson's medications with the r4 test patient profile. I can't remember if this is a problem that requires a work-around with r4, and I know you just updated this a day ago, but I figured I'd post the heads up, just it case.

**Comment by cmoesel** [comment]
Ah.  You found the code before I even sent out an email to announce it!  Although I pushed up a branch yesterday, it wasn't really complete until today.  Hopefully you have the latest from the master branch.

First, please note that the data for R4 Brenda is definitely _different_ than the data for the DSTU2 Brenda.  It's not just a difference in FHIR versions, but actually a difference because we _changed_ some of the entries -- mostly updating some dates so they fall within our "lookback" windows (and are consequently displayed in the app).  That's why R4 Brenda has more total entries than DSTU2 Brenda.

As for the missing medication end dates, however, that is because the FHIR spec _removed_ the `dateEnded` property when they changed `MedicationOrder` to `MedicationRequest`.  There is no longer a way to record an end date on medication requests -- so there's no way for the summary to display one.  That said `MedicationStatement` still supports `effectivePeriod`, which allows a start _and_ an end date.  So if there are `MedicationStatement`s in the record, the R4 Pain Management Summary _will_ show an end date for them (if the data contains it).

**Comment by maggiedorr** [comment]
> There is no longer a way to record an end date on medication requests -- so there's no way for the summary to display one. That said MedicationStatement still supports effectivePeriod, which allows a start and an end date. So if there are MedicationStatements in the record, the R4 Pain Management Summary will show an end date for them (if the data contains it).

Well. That's delightful[ly] annoying. But good to know. I guess we'll have to hope for the best with our records. 
Thanks!
