### ISSUE TITLE
"To build and run in development" Doesn't seem to work

### ISSUE THREAD

**Issue by bryantaustin13** [AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY#9]
I downloaded the project, ran "yarn" and "yarn start".  The system console shows:
![yarnStartCmdLine](https://user-images.githubusercontent.com/3997736/76317606-12ed7f80-62a2-11ea-885a-7e20b7b3e444.png)
 The console for Chrome at http://localhost:8000 shows:
Error: No 'state' parameter found. Please (re)launch the app.
    at completeAuth (smart.js:420)
console.<computed> @ index.js:1406

 According to the README.md, especially the section on building and running in development, this should work.
I do not have a unique "SMART-on-FHIR client ID".   Do I need one?  
System - Windows 10, Node v 12.13.0., git bash shell to run command line

**Comment by cmoesel** [comment]
Hi @bryantaustin13.  I think what you're describing is actually expected -- because the app can't run outside the context of an EHR (or EHR-simulating sandbox).  That's the `state` that's missing when it tries to run on its own.

Try running it the same way, but then following the instructions for testing it in the SMART sandbox, as documented here: https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY#to-test-the-app-using-the-public-smart-sandbox

When it's time to select a patient, I recommend "Brenda Jackson" (if that patient is available).

Let us know if that takes care of it!

**Comment by bryantaustin13** [comment]
Thanks for your quick response!
When trying that I tried Bradley Douglas (Brenda Jackson does not come up in search).  I still am getting the Chrome console error.  I see his name in the header and his id in the footer, but the center portion (where I am guessing the patient data or recommendations or something similar appears) shows ERROR: see console for details which then shows the state error.I get the same results with other patients I try as well.

Thanks!
    On Tuesday, March 10, 2020, 08:28:54 AM MDT, Chris Moesel <notifications@github.com> wrote:  
 
 
Hi @bryantaustin13. I think what you're describing is actually expected -- because the app can't run outside the context of an EHR (or EHR-simulating sandbox). That's the state that's missing when it tries to run on its own.

Try running it the same way, but then following the instructions for testing it in the SMART sandbox, as documented here: https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY#to-test-the-app-using-the-public-smart-sandbox

When it's time to select a patient, I recommend "Brenda Jackson" (if that patient is available).

Let us know if that takes care of it!

**Comment by bryantaustin13** [comment]
Interestingly if I use the url http://localhost:8000/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY/launch.html in the SMART App Launcher instead of just http://localhost:8000 it no longer shows the error.  Nothing happens on the page, but the patient (Mrs. Danae Kshlerin) show up in the header and her id in the footer.  What should I be seeing in a successful try?
Thanks!
    On Tuesday, March 10, 2020, 09:01:54 AM MDT, Bryant Austin <bryantaustin13@yahoo.com> wrote:  
 
  Thanks for your quick response!
When trying that I tried Bradley Douglas (Brenda Jackson does not come up in search).  I still am getting the Chrome console error.  I see his name in the header and his id in the footer, but the center portion (where I am guessing the patient data or recommendations or something similar appears) shows ERROR: see console for details which then shows the state error.I get the same results with other patients I try as well.

Thanks!
    On Tuesday, March 10, 2020, 08:28:54 AM MDT, Chris Moesel <notifications@github.com> wrote:  
 
 
Hi @bryantaustin13. I think what you're describing is actually expected -- because the app can't run outside the context of an EHR (or EHR-simulating sandbox). That's the state that's missing when it tries to run on its own.

Try running it the same way, but then following the instructions for testing it in the SMART sandbox, as documented here: https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY#to-test-the-app-using-the-public-smart-sandbox

When it's time to select a patient, I recommend "Brenda Jackson" (if that patient is available).

Let us know if that takes care of it!

**Comment by cmoesel** [comment]
I'm trying to reproduce this.  I did a clean clone of the repo, then ran `yarn`, followed by `yarn start`.  This launched my browser and did show an error page -- but that is expected.  I then used the SMART launcher with the following config:

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/2278253/76460622-b6c75000-63b4-11ea-9340-4922a6ba7d9f.png">


I selected _Mr. Bradley Douglas_ and received this page:

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/2278253/76460572-9b5c4500-63b4-11ea-9030-e8cbc63d70f2.png">

Since Bradley doesn't match the inclusion criteria, that's expected.  So... I'm getting the expected behavior using a fresh build.

Maybe this comes down to environment?  What operating system are you on (Windows/Mac)? What version of Node.js and Yarn?  And what browser?

**Comment by bryantaustin13** [comment]
Finally, finally have the dashboard running.  Using a git bash shell to launch yarn uses a weird windows hybrid for paths.  Using Windows powershell doesn't help.  But using Windows 10 ubuntu Linux with the right versions (node, yarn, etc ) installed does work.

**Comment by cmoesel** [comment]
Yikes.  Thanks for the update and thanks for working through that.  It's too bad that there weren't more obvious error messages to clue you in on the problem.  I doubt we've tried it with git bash shell, but I thought we would have run into the powershell issue by now...
